version: '3.9'

services:
  webapi:
    container_name: web_api_test
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    # build image name > name:version
    image: webapi:latest
    networks:
      # network name
      - webapi_app
      # webapi_app:
        # ipv4_address: 172.18.0.2
    ports:
      # expose port > port:container port
      - 8088:80
      - 488:443
    volumes:
      # mount directory to container directory > path:container path
      # SSL credentials
      - C:/Users/User/.aspnet/https:/https
    environment:
      #- ASPNETCORE_URLS=http://+:80
      # donet core SSL credential environment settings
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=123
      # Starting with .NET 5, Kestrel can take the .crt and PEM-encoded .key files
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/contoso.com.crt
      # - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/contoso.com.key
networks:
  # network name
  webapi_app:
    driver: bridge
    name: webapi_app
    # ip address management
    # ipam:
    #   driver: default
    #   config:
    #       # Subnet in CIDR format that represents a network segment
    #     - subnet: 172.28.0.0/16
    #       # Range of IPs from which to allocate container IPs
    #       ip_range: 172.28.5.0/24
    #       # IPv4 or IPv6 gateway for the master subnet
    #       gateway: 172.28.5.254
    #       # Auxiliary IPv4 or IPv6 addresses used by Network driver, as a mapping from hostname to IP
    #       aux_addresses:
    #         host1: 172.28.1.5
    #         host2: 172.28.1.6
    #         host3: 172.28.1.7